import type { Metadata } from "next";
import "./styles/globals.css";
import Header from "@/components/ui/header/Header";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html lang="en" className="antialiased">
                <body>
                    <Header />
                    {children}
                </body>
            </html>
        </ViewTransitions>
    );
}
