export const projectData = [
    {
        title: "Kummelnäshöjden",
        introText:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula feugiat ligula. Cras non volutpat mauris. Aliquam consectetur faucibus euismod. Aliquam vel feugiat urna. Nullam condimentum, nunc sit amet volutpat sodales, mauris leo ultricies mi, eu accumsan elit erat bibendum nisl.",
        showcaseImages: [
            "/projects/kummelnashojden/Interior_3_002.webp",
            "/projects/kummelnashojden/Interior_7_002.webp",
            "/projects/kummelnashojden/Interior_5_003.webp",
            "/projects/kummelnashojden/Exterior_3_Wood_002.webp",
            "/projects/kummelnashojden/Exterior_1_Wood_002.webp",
        ],
        galleryImages: [
            "/projects/kummelnashojden/Exterior_1_Back_Black_003.webp",
            "/projects/kummelnashojden/Exterior_1_Black_002.webp",
            "/projects/kummelnashojden/Exterior_1_Wood_002.webp",
            "/projects/kummelnashojden/Exterior_2_Back_Black_002.webp",
            "/projects/kummelnashojden/Exterior_2_Back_Wood_002.webp",
            "/projects/kummelnashojden/Exterior_2_Black_001.webp",
            "/projects/kummelnashojden/Exterior_2_Wood_002.webp",
            "/projects/kummelnashojden/Exterior_3_Black_002.webp",
            "/projects/kummelnashojden/Exterior_3_Wood_002.webp",
            "/projects/kummelnashojden/Interior_1_002.webp",
            "/projects/kummelnashojden/Interior_2_002.webp",
            "/projects/kummelnashojden/Interior_3_002.webp",
            "/projects/kummelnashojden/Interior_4_002.webp",
            "/projects/kummelnashojden/Interior_5_003.webp",
            "/projects/kummelnashojden/Interior_6_002.webp",
            "/projects/kummelnashojden/Interior_7_002.webp",
        ],
        objectInfo: {
            buildStart: "2027",
            moveIn: "2028",
            estateAmount: "4",
            roomAmount: "5",
            size: "80kvm",
            energyClass: "A",
        },
        aboutText:
            "Kummelnäshöjden är ett exklusivt bostadsprojekt beläget på Lidingö, med enastående utsikt över Stockholms skärgård. Husen är ritade av Wingårdhs arkitektkontor och uppförs i massivt trä med en tidlös, nordisk estetik. Varje bostad är unikt utformad med generösa takhöjder, stora fönsterpartier och privata uteplats. Materialen är noggrant utvalda för att skapa en varm och hållbar hemmiljö som håller i generationer.",
        placement: [
            "8 min till tunnelbana",
            "15 min till city",
            "Natur direkt utanför",
            "Lidingö centrum 5 min",
            "Skolor i närområdet",
        ],
        sustainability: [
            "Massivt KL-trä",
            "Bergvärme",
            "Solceller på taket",
            "Energiklass A",
            "Laddstolpe ingår",
            "Grönt tak",
        ],
    },
    {
        title: "Glansbaggen",
        introText:
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vehicula feugiat ligula. Cras non volutpat mauris. Aliquam consectetur faucibus euismod. Aliquam vel feugiat urna. Nullam condimentum, nunc sit amet volutpat sodales, mauris leo ultricies mi, eu accumsan elit erat bibendum nisl.",
        showcaseImages: [
            "/projects/glansbaggen/Glansbaggen_kök_001.webp",
            "/projects/glansbaggen/Glansbaggen_exterior_2_002.webp",
            "/projects/glansbaggen/Glansbaggen_Vardagsrum_001.webp",
            "/projects/glansbaggen/Glansbaggen_badrum_001.webp",
            "/projects/glansbaggen/Glansbaggen_Sovrum_001.webp",
        ],
        galleryImages: [
            "/projects/glansbaggen/Glansbaggen_badrum_001.webp",
            "/projects/glansbaggen/Glansbaggen_barnrum_001.webp",
            "/projects/glansbaggen/Glansbaggen_exterior_1_002.webp",
            "/projects/glansbaggen/Glansbaggen_exterior_2_002.webp",
            "/projects/glansbaggen/Glansbaggen_exterior_3_002.webp",
            "/projects/glansbaggen/Glansbaggen_kök_001.webp",
            "/projects/glansbaggen/Glansbaggen_kök_2_001.webp",
            "/projects/glansbaggen/Glansbaggen_Övre_hall_001.webp",
            "/projects/glansbaggen/Glansbaggen_Sovrum_001.webp",
            "/projects/glansbaggen/Glansbaggen_Vardagsrum_001.webp",
        ],
        objectInfo: {
            buildStart: "2026",
            moveIn: "2027",
            estateAmount: "6",
            roomAmount: "4",
            size: "70kvm",
            energyClass: "B",
        },
        aboutText:
            "Glansbaggen är ett modernt bostadsprojekt beläget i ett lugnt och naturnära område med goda kommunikationer. Husen uppförs med hög kvalitet och modern arkitektur, med fokus på ljusa och öppna planlösningar. Varje bostad erbjuder generösa ytor, smarta förvaringslösningar och privata uteplats. Materialen är noggrant utvalda för att skapa en trivsam och hållbar hemmiljö.",
        placement: [
            "10 min till tunnelbana",
            "20 min till city",
            "Natur direkt utanför",
            "Centrum 7 min",
            "Skolor i närområdet",
        ],
        sustainability: [
            "Massivt KL-trä",
            "Bergvärme",
            "Solceller på taket",
            "Energiklass B",
            "Laddstolpe ingår",
            "Grönt tak",
        ],
    },
];
